In [50]:
import urllib2
import warnings
warnings.filterwarnings('ignore')

import simplejson as json
import ujson
import numpy as np
import pandas as pd

In [85]:
def fetchAPIdata(movie):
    
    if movie == "Moonlight (2016)":
        movie = "Moonlight"
    
    if movie == "Birdman":
        url = 'http://www.omdbapi.com/?t={}&y=2014'.format(movie)
        return(ujson.loads(urllib2.urlopen(url).read()))
    
    movie = "+".join((movie.split(" ")))
    url = 'http://www.omdbapi.com/?t={}'.format(movie)
    
    movie = ujson.loads(urllib2.urlopen(url).read())
    
#     record = {}
#     record['MOVIE'] = movie['Title']
#     record['awards'] =  movie['Awards']
#     record['metascore'] =  movie['Metascore']
#     record['imdbRating'] =  movie['imdbRating']
#     record['released'] = movie['Released']
#     record['rated'] =  movie['Rated']
#     record['director'] =  movie['Director']
#     record['actors'] =  movie['Actors']
#     record['runtime'] =  movie['Runtime']
#     record['genre'] =  movie['Genre']
#     record['plot'] =  movie['Plot']
#     record['rottentomatoes'] = (movie['Ratings'][1]['Value']).split("%")[0]
    
    
    
    
    return(movie)

In [86]:
movies = pd.read_csv("oscars.csv")['MOVIE']
oscars = [fetchAPIdata(movie) for movie in movies]
oscars = pd.DataFrame(oscars)
oscars

,Actors,Awards,BoxOffice,Country,DVD,Director,Error,Genre,Language,Metascore,...,Response,Runtime,Title,Type,Website,Writer,Year,imdbID,imdbRating,imdbVotes
0,"Mahershala Ali, Shariff Earp, Duan Sanderson, ...",Won 3 Oscars. Another 197 wins & 239 nominations.,"$27,806,908.00",USA,28 Feb 2017,Barry Jenkins,NaN,Drama,English,99,...,True,111 min,Moonlight,movie,http://moonlight.movie/,"Barry Jenkins (screenplay), Tarell Alvin McCra...",2016,tt4975722,7.6,"122,516"
1,"Mark Ruffalo, Michael Keaton, Rachel McAdams, ...",Won 2 Oscars. Another 116 wins & 132 nominations.,N/A,"USA, Canada",23 Feb 2016,Tom McCarthy,NaN,"Crime, Drama, History",English,93,...,True,128 min,Spotlight,movie,http://SpotlightTheFilm.com,"Josh Singer, Tom McCarthy",2015,tt1895587,8.1,"258,883"
2,N/A,N/A,N/A,UK,17 Feb 2015,Guy Bolongaro,NaN,Documentary,N/A,N/A,...,True,13 min,Birdman,movie,http://www.birdmanthemovie.com/,N/A,2014,tt5130912,4.9,116
3,"Chiwetel Ejiofor, Dwight Henry, Dickie Gravois...",Won 3 Oscars. Another 234 wins & 320 nominations.,"$50,628,650.00","USA, UK",04 Mar 2014,Steve McQueen,NaN,"Biography, Drama, History",English,96,...,True,134 min,12 Years a Slave,movie,http://www.foxsearchlight.com/12yearsaslave/,"John Ridley (screenplay), Solomon Northup (bas...",2013,tt2024544,8.1,"482,607"
4,"Ben Affleck, Bryan Cranston, Alan Arkin, John ...",Won 3 Oscars. Another 93 wins & 150 nominations.,"$136,019,448.00",USA,19 Feb 2013,Ben Affleck,NaN,"Biography, Drama, History","English, Persian, Arabic",86,...,True,120 min,Argo,movie,http://argothemovie.warnerbros.com,"Chris Terrio (screenplay), Tony Mendez (based ...",2012,tt1024648,7.7,"477,124"
5,"Jean Dujardin, Bérénice Bejo, John Goodman, Ja...",Won 5 Oscars. Another 146 wins & 185 nominations.,"$44,667,095.00","France, USA, Belgium",26 Jun 2012,Michel Hazanavicius,NaN,"Comedy, Drama, Romance","English, English, French",89,...,True,100 min,The Artist,movie,http://theartistmovie.net,Michel Hazanavicius,2011,tt1655442,7.9,"198,801"
6,"Colin Firth, Helena Bonham Carter, Derek Jacob...",Won 4 Oscars. Another 102 wins & 190 nominations.,"$138,300,000.00","UK, USA, Australia",19 Apr 2011,Tom Hooper,NaN,"Biography, Drama",English,88,...,True,118 min,The King's Speech,movie,http://www.kingsspeech.com/,David Seidler (screenplay),2010,tt1504320,8.0,"529,794"
7,"Jeremy Renner, Anthony Mackie, Brian Geraghty,...",Won 6 Oscars. Another 114 wins & 120 nominations.,"$15,700,000.00",USA,12 Jan 2010,Kathryn Bigelow,NaN,"Drama, History, Thriller","English, Arabic",94,...,True,131 min,The Hurt Locker,movie,http://www.thehurtlocker-movie.com/,Mark Boal,2008,tt0887912,7.6,"349,219"
8,"Dev Patel, Saurabh Shukla, Anil Kapoor, Raj Zu...",Won 8 Oscars. Another 143 wins & 120 nominations.,"$141,243,551.00","UK, France, USA",31 Mar 2009,"Danny Boyle, Loveleen Tandan",NaN,Drama,"English, Hindi, French",86,...,True,120 min,Slumdog Millionaire,movie,http://www.foxsearchlight.com/slumdogmillionaire/,"Simon Beaufoy (screenplay), Vikas Swarup (novel)",2008,tt1010048,8.0,"673,828"
9,"Tommy Lee Jones, Javier Bardem, Josh Brolin, W...",Won 4 Oscars. Another 155 wins & 132 nominations.,"$74,223,625.00",USA,07 Apr 2009,"Ethan Coen, Joel Coen",NaN,"Crime, Drama, Thriller","English, Spanish",91,...,True,122 min,No Country for Old Men,movie,http://www.nocountryforoldmen-themovie.com,"Joel Coen (screenplay), Ethan Coen (screenplay...",2007,tt0477348,8.1,"652,793"
10,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",Won 4 Oscars. Another 90 wins & 126 nominations.,"$132,300,000.00","USA, Hong Kong",13 Feb 2007,Martin Scorsese,NaN,"Crime, Drama, Thriller","English, Cantonese",85,...,True,151 min,The Departed,movie,http://www.thedeparted.com/,"William Monahan (screenplay), Alan Mak, Felix ...",2006,tt0407887,8.5,"932,260"
11,"Karina Arroyave, Dato Bakhtadze, Sandra Bulloc...",Won 3 Oscars. Another 62 wins & 106 nominations.,"$55,382,847.00","Germany, USA",06 Sep 2005,Paul Haggis,NaN,"Crime, Drama, Thriller","English, Persian, Spanish, Mandarin, Korean",69,...,True,112 min,Crash,movie,http://www.crashfilm.com/,"Paul Haggis (story), Paul Haggis (screenplay),...",2004,tt0375679,7.8,"371,948"
12,"Clint Eastwood, Hilary Swank, Morgan Freeman, ...",Won 4 Oscars. Another 63 wins & 78 nominations.,"$100,422,786.00",USA,12 Jul 2005,Clint Eastwood,NaN,"Drama, Sport","English, Irish",86,...,True,132 min,Million Dollar Baby,movie,http://milliondollarbabymovie.warnerbros.com/,"Paul Haggis (screenplay), F.X. Toole (stories)",2004,tt0405159,8.1,"513,286"
13,"Noel Appleby, Ali Astin, Sean Astin, David Aston",Won 11 Oscars. Another 195 wins & 121 nominati...,"$364,000,000.00","USA, New Zealand",25 May 2004,Peter Jackson,NaN,"Adventure, Drama, Fantasy","English, Quenya, Old English, Sindarin",94,...,True,201 min,The Lord of the Rings: The Return of the King,movie,http://www.lordoftherings.net/,"J.R.R. Tolkien (novel), Fran Walsh (screenplay...",2003,tt0167260,8.9,"1,289,043"
14,"Taye Diggs, Cliff Saunders, Catherine Zeta-Jon...",Won 6 Oscars. Another 50 wins & 122 nominations.,N/A,"USA, Germany, Canada",19 Aug 2003,Rob Marshall,NaN,"Comedy, Crime, Musical","English, Hungarian",82,...,True,113 min,Chicago,movie,http://www.miramax.com/movie/chicago,"Bill Condon (screenplay), Bob Fosse (book), Fr...",2002,tt0299658,7.2,"180,729"
15,"Russell Crowe, Ed Harris, Jennifer Connelly, C...",Won 4 Oscars. Another 33 wins & 65 nominations.,N/A,USA,25 Jun 2002,Ron Howard,NaN,"Biography, Drama",English,72,...,True,135 min,A Beautiful Mind,movie,http://www.abeautifulmind.com,"Akiva Goldsman, Sylvia Nasar (book)",2001,tt0268978,8.2,"658,210"
16,"Russell Crowe, Joaquin Phoenix, Connie Nielsen...",Won 5 Oscars. Another 53 wins & 101 nominations.,N/A,"USA, UK",21 Nov 2000,Ridley Scott,NaN,"Action, Adventure, Drama",English,64,...,True,155 min,Gladiator,movie,http://www.gladiator-thefilm.com,"David Franzoni (story), David Franzoni (screen...",2000,tt0172495,8.5,"1,045,850"
17,"Kevin Spacey, Annette Bening, Thora Birch, Wes...",Won 5 Oscars. Another 103 wins & 96 nominations.,N/A,USA,02 Jan 2002,Sam Mendes,NaN,"Drama, Romance",English,86,...,True,122 min,American Beauty,movie,http://www.amazon.com/exec/obidos/subst/video/...,Alan Ball,1999,tt0169547,8.4,"870,647"
18,"Geoffrey Rush, Tom Wilkinson, Steven O'Donnell...",Won 7 Oscars. Another 56 wins & 88 nominations.,N/A,"USA, UK",10 Aug 1999,John Madden,NaN,"Comedy, Drama, History",English,87,...,True,123 min,Shakespeare in Love,movie,http://www.miramax.com/mm_front/owa/mp.entryPo...,"Marc Norman, Tom Stoppard",1998,tt0138097,7.2,"182,412"
19,"Leonardo DiCaprio, Kate Winslet, Billy Zane, K...",Won 11 Oscars. Another 110 wins & 74 nominations.,N/A,USA,10 Sep 2012,James Cameron,NaN,"Drama, Romance","English, Swedish",74,...,True,194 min,Titanic,movie,http://www.titanicmovie.com/,James Cameron,1997,tt0120338,7.7,"838,917"
20,"Ralph Fiennes, Juliette Binoche, Willem Dafoe,...",Won 9 Oscars. Another 50 wins & 66 nominations.,N/A,"USA, UK",24 Mar 1998,Anthony Minghella,NaN,"Drama, Romance, War","English, German, Italian, Arabic",87,...,True,162 min,The English Patient,movie,N/A,"Michael Ondaatje (novel), Anthony Minghella (s...",1996,tt0116209,7.4,"149,126"
21,"James Robinson, Sean Lawlor, Sandy Nelson, Jam...",Won 5 Oscars. Another 26 wins & 29 nominations.,N/A,USA,29 Aug 2000,Mel Gibson,NaN,"Biography, Drama, History","English, French, Latin, Scottish Gaelic",68,...,True,178 min,Braveheart,movie,N/A,Randall Wallace,1995,tt0112573,8.4,"776,743"
22,"Tom Hanks, Rebecca Williams, Sally Field, Mich...",Won 6 Oscars. Another 39 wins & 65 nominations.,"$405,000.00",USA,28 Aug 2001,Robert Zemeckis,NaN,"Comedy, Drama, Romance",English,82,...,True,142 min,Forrest Gump,movie,http://www.paramount.com/movies/forrest-gump/,"Winston Groom (novel), Eric Roth (screenplay)",1994,tt0109830,8.8,"1,345,295"
23,"Liam Neeson, Ben Kingsley, Ralph Fiennes, Caro...",Won 7 Oscars. Another 71 wins & 33 nominations.,N/A,USA,09 Mar 2004,Steven Spielberg,NaN,"Biography, Drama, History","English, Hebrew, German, Polish",93,...,True,195 min,Schindler's List,movie,http://www.schindlerslist.com,"Thomas Keneally (book), Steven Zaillian (scree...",1993,tt0108052,8.9,"917,046"
24,"Clint Eastwood, Gene Hackman, Morgan Freeman, ...",Won 4 Oscars. Another 36 wins & 29 nominations.,N/A,USA,26 Mar 1997,Clint Eastwood,NaN,"Drama, Western",English,82,...,True,131 min,Unforgiven,movie,N/A,David Webb Peoples,1992,tt0105695,8.3,"293,918"
25,"Jodie Foster, Lawrence A. Bonney, Kasi Lemmons...",Won 5 Oscars. Another 48 wins & 36 nominations.,N/A,USA,01 Jul 1998,Jonathan Demme,NaN,"Crime, Drama, Thriller",English,84,...,True,118 min,The Silence of the Lambs,movie,N/A,"Thomas Harris (novel), Ted Tally (screenplay)",1991,tt0102926,8.6,"954,517"
26,"Kevin Costner, Mary McDonnell, Graham Greene, ...",Won 7 Oscars. Another 43 wins & 33 nominations.,N/A,"USA, UK",17 Jun 2003,Kevin Costner,NaN,"Adventure, Drama, Western","English, Sioux, Pawnee",72,...,True,181 min,Dances with Wolves,movie,N/A,"Michael Blake (screenplay), Michael Blake (novel)",1990,tt0099348,8.0,"196,512"
27,"Morgan Freeman, Jessica Tandy, Dan Aykroyd, Pa...",Won 4 Oscars. Another 17 wins & 21 nominations.,N/A,USA,29 Apr 1997,Bruce Beresford,NaN,Drama,"English, Hebrew",81,...,True,99 min,Driving Miss Daisy,movie,http://www.broadwaynearyou.com/driving-miss-da...,"Alfred Uhry (screenplay), Alfred Uhry (play)",1989,tt0097239,7.4,"76,768"
28,"Dustin Hoffman, Tom Cruise, Valeria Golino, Ge...",Won 4 Oscars. Another 22 wins & 21 nominations.,N/A,USA,01 Jan 2000,Barry Levinson,NaN,Drama,"English, Italian",65,...,True,133 min,Rain Man,movie,N/A,"Barry Morrow (story), Ronald Bass (screenplay)...",1988,tt0095953,8.0,"399,702"
29,"John Lone, Joan Chen, Peter O'Toole, Ruocheng ...",Won 9 Oscars. Another 47 wins & 16 nominations.,N/A,"China, Italy, UK, France, USA",20 Mar 2001,Bernardo Bertolucci,NaN,"Biography, Drama, History","English, Mandarin, Japanese, Russian",76,...,True,163 min,The Last Emperor,movie,N/A,"Mark Peploe (screenplay), Bernardo Bertolucci ...",1987,tt0093389,7.8,"74,166"
30,"Tom Berenger, Keith David, Willem Dafoe, Fores...",Won 4 Oscars. Another 19 wins & 14 nominations.,N/A,"UK, USA",09 Dec 1997,Oliver Stone,NaN,"Drama, War","English, Vietnamese",N/A,...,True,120 min,Platoon,movie,N/A,Oliver Stone,1986,tt0091763,8.1,"307,746"
31,"Meryl Streep, Robert Redford, Klaus Maria Bran...",Won 7 Oscars. Another 22 wins & 28 nominations.,N/A,"USA, UK",29 Jan 2002,Sydney Pollack,NaN,"Biography, Drama, Romance","English, Swahili",N/A,...,True,161 min,Out of Africa,movie,N/A,"Karen Blixen (based upon: ""Out of Africa"" and ...",1985,tt0089755,7.2,"55,490"
32,"F. Murray Abraham, Tom Hulce, Elizabeth Berrid...",Won 8 Oscars. Another 33 wins & 14 nominations.,N/A,"USA, France",16 Dec 1997,Milos Forman,NaN,"Biography, Drama, History","English, Italian, Latin, German",93,...,True,160 min,Amadeus,movie,http://movies.warnerbros.com/amadeus,"Peter Shaffer (original stage play), Peter Sha...",1984,tt0086879,8.3,"287,352"
33,"Shirley MacLaine, Debra Winger, Jack Nicholson...",Won 5 Oscars. Another 27 wins & 18 nominations.,N/A,USA,10 Apr 2001,James L. Brooks,NaN,"Comedy, Drama",English,79,...,True,132 min,Terms of Endearment,movie,N/A,"Larry McMurtry (based on the novel by), James ...",1983,tt0086425,7.4,"42,721"
34,"Ben Kingsley, Candice Bergen, Edward Fox, John...",Won 8 Oscars. Another 27 wins & 20 nominations.,N/A,"UK, India, USA",28 Aug 2001,Richard Attenborough,NaN,"Biography, Drama, History",English,N/A,...,True,191 min,Gandhi,movie,N/A,John Briley,1982,tt0083987,8.1,"182,001"
35,"Nicholas Farrell, Nigel Havers, Ian Charleson,...",Won 4 Oscars. Another 14 wins & 19 nominations.,N/A,UK,27 Aug 1997,Hugh Hudson,NaN,"Biography, Drama, Sport","English, French",N/A,...,True,125 min,Chariots of Fire,movie,N/A,Colin Welland (original screenplay),1981,tt0082158,7.2,"42,838"
36,"Donald Sutherland, Mary Tyler Moore, Judd Hirs...",Won 4 Oscars. Another 15 wins & 14 nominations.,N/A,USA,14 Aug 2001,Robert Redford,NaN,Drama,English,85,...,True,124 min,Ordinary People,movie,N/A,"Judith Guest (novel), Alvin Sargent (screenplay)",1980,tt0081283,7.8,"36,919"
37,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"Robert De Niro, John Cazale, John Savage, Chri...",Won 5 Oscars. Another 17 wins & 26 nominations.,N/A,USA,06 Sep 2005,Michael Cimino,NaN,"Drama, War","English, Russian, Vietnamese, French",73,...,True,183 min,The Deer Hunter,movie,N/A,"Michael Cimino (story), Deric Washburn (story)...",1978,tt0077416,8.2,"244,695"

In [88]:
oscars['Ratings'].Source

AttributeError: 'Series' object has no attribute 'Source'

In [13]:
movie[0][1]

u'"'

In [7]:
# movies = np.array((pd.read_csv("oscars.csv"))['MOVIE'])
movies = ['Moonlight (2016)', 'Spotlight', 'Birdman', '12 Years a Slave',
       'Argo', 'The Artist', "The King's Speech", 'The Hurt Locker',
       'Slumdog Millionaire', 'No Country for Old Men', 'The Departed',
       'Crash', 'Million Dollar Baby',
       'The Lord of the Rings: The Return of the King', 'Chicago',
       'A Beautiful Mind', 'Gladiator', 'American Beauty',
       'Shakespeare in Love', 'Titanic', 'The English Patient',
       'Braveheart', 'Forrest Gump', "Schindler's List", 'Unforgiven',
       'The Silence of the Lambs', 'Dances with Wolves',
       'Driving Miss Daisy', 'Rain Man', 'The Last Emperor', 'Platoon',
       'Out of Africa', 'Amadeus', 'Terms of Endearment', 'Gandhi',
       'Chariots of Fire', 'Ordinary People', 'Kramer Vs. Kramer',
       'The Deer Hunter']

oscars = [getOMDBdata(movie) for movie in movies]
table = pd.DataFrame(oscars)
table['Title'] = movies
table

,RT_audience_perc,RT_audience_rating,RT_consensus,RT_perc,RT_rating,awards,imdb_rating,metascore,plot,Title
0,N/A,N/A,N/A,N/A,N/A,Won 3 Oscars. Another 197 wins & 239 nominations.,7.6,99,"Three time periods - young adolescence, mid-te...",Moonlight (2016)
1,N/A,N/A,N/A,N/A,N/A,Won 2 Oscars. Another 116 wins & 132 nominations.,8.1,93,"When the Boston Globe's tenacious ""Spotlight"" ...",Spotlight
2,N/A,N/A,N/A,N/A,N/A,N/A,6.9,N/A,A winged superhero who gets his powers from th...,Birdman
3,N/A,N/A,N/A,N/A,N/A,Won 3 Oscars. Another 234 wins & 320 nominations.,8.1,96,Based on an incredible true story of one man's...,12 Years a Slave
4,N/A,N/A,N/A,N/A,N/A,Won 3 Oscars. Another 93 wins & 150 nominations.,7.7,86,"In 1979, the American embassy in Iran was inva...",Argo
5,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 146 wins & 185 nominations.,7.9,89,"Outside a movie premiere, enthusiastic fan Pep...",The Artist
6,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 102 wins & 190 nominations.,8.0,88,England's Prince Albert must ascend the throne...,The King's Speech
7,N/A,N/A,N/A,N/A,N/A,Won 6 Oscars. Another 114 wins & 120 nominations.,7.6,94,An intense portrayal of elite soldiers who hav...,The Hurt Locker
8,N/A,N/A,N/A,N/A,N/A,Won 8 Oscars. Another 143 wins & 120 nominations.,8.0,86,"The story of Jamal Malik, an 18 year-old orpha...",Slumdog Millionaire
9,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 155 wins & 132 nominations.,8.1,91,"In rural Texas, welder and hunter Llewelyn Mos...",No Country for Old Men
10,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 90 wins & 126 nominations.,8.5,85,"In South Boston, the state police force is wag...",The Departed
11,N/A,N/A,N/A,N/A,N/A,Won 3 Oscars. Another 62 wins & 106 nominations.,7.8,69,"Over a thirty-six hour period in Los Angeles, ...",Crash
12,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 63 wins & 78 nominations.,8.1,86,"Wanting to learn from the best, aspiring boxer...",Million Dollar Baby
13,N/A,N/A,N/A,N/A,N/A,Won 11 Oscars. Another 195 wins & 121 nominati...,8.9,94,The final confrontation between the forces of ...,The Lord of the Rings: The Return of the King
14,N/A,N/A,N/A,N/A,N/A,Won 6 Oscars. Another 50 wins & 122 nominations.,7.2,82,Murderesses Velma Kelly (a chanteuse and tease...,Chicago
15,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 33 wins & 65 nominations.,8.2,72,From the heights of notoriety to the depths of...,A Beautiful Mind
16,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 53 wins & 101 nominations.,8.5,64,"Maximus is a powerful Roman general, loved by ...",Gladiator
17,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 103 wins & 96 nominations.,8.4,86,"Lester and Carolyn Burnham are, on the outside...",American Beauty
18,N/A,N/A,N/A,N/A,N/A,Won 7 Oscars. Another 56 wins & 88 nominations.,7.2,87,Will Shakespeare is a known but struggling poe...,Shakespeare in Love
19,N/A,N/A,N/A,N/A,N/A,Won 11 Oscars. Another 110 wins & 74 nominations.,7.7,74,"84 years later, a 101-year-old woman named Ros...",Titanic
20,N/A,N/A,N/A,N/A,N/A,Won 9 Oscars. Another 50 wins & 66 nominations.,7.4,87,"October 1944 in war torn Italy. Hana, a French...",The English Patient
21,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 26 wins & 29 nominations.,8.4,68,William Wallace is a Scottish rebel who leads ...,Braveheart
22,N/A,N/A,N/A,N/A,N/A,Won 6 Oscars. Another 39 wins & 65 nominations.,8.8,82,Forrest Gump is a simple man with a low I.Q. b...,Forrest Gump
23,N/A,N/A,N/A,N/A,N/A,Won 7 Oscars. Another 71 wins & 33 nominations.,8.9,93,Oskar Schindler is a vainglorious and greedy G...,Schindler's List
24,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 36 wins & 29 nominations.,8.3,82,The town of Big Whisky is full of normal peopl...,Unforgiven
25,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 48 wins & 36 nominations.,8.6,84,FBI trainee Clarice Starling works hard to adv...,The Silence of the Lambs
26,N/A,N/A,N/A,N/A,N/A,Won 7 Oscars. Another 43 wins & 33 nominations.,8.0,72,Lt. John Dunbar is dubbed a hero after he acci...,Dances with Wolves
27,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 17 wins & 21 nominations.,7.4,81,An elderly Jewish widow living in Atlanta can ...,Driving Miss Daisy
28,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 22 wins & 21 nominations.,8.0,65,"Charles Sanford ""Charlie"" Babbit is a self-cen...",Rain Man
29,N/A,N/A,N/A,N/A,N/A,Won 9 Oscars. Another 47 wins & 16 nominations.,7.8,76,"This sweeping account of the life of Pu-Yi, th...",The Last Emperor
30,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 19 wins & 14 nominations.,8.1,N/A,"Chris Taylor is a young, naive American who gi...",Platoon
31,N/A,N/A,N/A,N/A,N/A,Won 7 Oscars. Another 22 wins & 28 nominations.,7.2,N/A,"In 20th-century colonial Kenya, a Danish baron...",Out of Africa
32,N/A,N/A,N/A,N/A,N/A,Won 8 Oscars. Another 33 wins & 14 nominations.,8.3,93,Antonio Salieri believes that Wolfgang Amadeus...,Amadeus
33,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 27 wins & 18 nominations.,7.4,79,Aurora and Emma are mother and daughter who ma...,Terms of Endearment
34,N/A,N/A,N/A,N/A,N/A,Won 8 Oscars. Another 27 wins & 20 nominations.,8.1,N/A,"In 1893, Gandhi is thrown off a South African ...",Gandhi
35,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 14 wins & 19 nominations.,7.2,N/A,It's the post-WWI era. Britons Harold Abrahams...,Chariots of Fire
36,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 15 wins & 14 nominations.,7.8,85,"Beth, Calvin, and their son Conrad are living ...",Ordinary People
37,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 32 wins & 23 nominations.,7.8,77,Ted Kramer is a career man for whom his work c...,Kramer Vs. Kramer
38,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 17 wins & 26 nominations.,8.2,73,"Michael, Steven and Nick are young factory wor...",The Deer Hunter

In [8]:
getOMDBdata("Man of Steel")

{'RT_audience_perc': u'N/A',
 'RT_audience_rating': u'N/A',
 'RT_consensus': u'N/A',
 'RT_perc': u'N/A',
 'RT_rating': u'N/A',
 'awards': u'7 wins & 45 nominations.',
 'imdb_rating': u'7.1',
 'metascore': u'55',
 'plot': u'Clark Kent, one of the last of an extinguished race disguised as an unremarkable human, is forced to reveal his identity when Earth is invaded by an army of survivors who threaten to bring the planet to the brink of destruction.'}

In [9]:
omdb.get(title='Moonlight', fullplot=True, tomatoes=True)

Item({'metascore': u'99', 'year': u'2016', 'tomato_rating': u'N/A', 'tomato_meter': u'N/A', 'plot': u"Three time periods - young adolescence, mid-teen and young adult - in the life of African-American, gay Chiron is presented. When a child, Chiron lives with his single, crack addict mother, Paula, in a crime-ridden neighborhood in Miami. Chiron is a shy, withdrawn child largely due to his small size and being neglected by his mother, who is more concerned about getting her fixes and satisfying her carnal needs than taking care of him. Because of these issues, Chiron is bullied, the slurs hurled at him which he doesn't understand beyond knowing that they are meant to be hurtful. Besides his same-aged Cuban-American friend Kevin, Chiron is given what little guidance he has in life from a neighborhood drug dealer named Juan, who can see that he is neglected, and Juan's caring girlfriend Teresa, whose home acts as a sanctuary away from the bullies and away from Paula's abuse. With this childhood as a foundation, Chiron may have a predetermined path in life, one that will only be magnified in terms of its problems when he reaches his difficult teen years when peer pressure affects what he and many of his peers do, unless he follows Juan's advice of truly making his own decisions for himself.", 'rated': u'R', 'tomato_rotten': u'N/A', 'title': u'Moonlight', 'tomato_consensus': u'N/A', 'writer': u'Barry Jenkins (screenplay), Tarell Alvin McCraney (story by)', 'tomato_user_meter': u'N/A', 'production': u'A24 Films', 'actors': u'Mahershala Ali, Shariff Earp, Duan Sanderson, Alex R. Hibbert', 'tomato_fresh': u'N/A', 'imdb_votes': u'122,516', 'type': u'movie', 'tomato_user_reviews': u'N/A', 'website': u'http://moonlight.movie/', 'poster': u'https://images-na.ssl-images-amazon.com/images/M/MV5BNzQxNTIyODAxMV5BMl5BanBnXkFtZTgwNzQyMDA3OTE@._V1_SX300.jpg', 'imdb_id': u'tt4975722', 'director': u'Barry Jenkins', 'released': u'18 Nov 2016', 'tomato_reviews': u'N/A', 'awards': u'Won 3 Oscars. Another 197 wins & 239 nominations.', 'tomato_user_rating': u'N/A', 'genre': u'Drama', 'response': u'True', 'language': u'English', 'dvd': u'28 Feb 2017', 'imdb_rating': u'7.6', 'country': u'USA', 'tomato_image': u'N/A', 'runtime': u'111 min', 'box_office': u'$27,806,908.00'})

In [6]:
titles = ['Moonlight (2016)', 'Spotlight', 'Birdman', '12 Years a Slave',
       'Argo', 'The Artist', "The King's Speech", 'The Hurt Locker',
       'Slumdog Millionaire', 'No Country for Old Men', 'The Departed',
       'Crash', 'Million Dollar Baby',
       'The Lord of the Rings: The Return of the King', 'Chicago',
       'A Beautiful Mind', 'Gladiator', 'American Beauty',
       'Shakespeare in Love', 'Titanic', 'The English Patient',
       'Braveheart', 'Forrest Gump', "Schindler's List", 'Unforgiven',
       'The Silence of the Lambs', 'Dances with Wolves',
       'Driving Miss Daisy', 'Rain Man', 'The Last Emperor', 'Platoon',
       'Out of Africa', 'Amadeus', 'Terms of Endearment', 'Gandhi',
       'Chariots of Fire', 'Ordinary People', 'Kramer Vs. Kramer',
       'The Deer Hunter']

In [4]:
# %%capture

oscars = [getOMDBdata(title) for title in oscars]
# oscars = Parallel(n_jobs=num_cores)(delayed(getOMDBdata)(title) for title in oscars)
table = pd.DataFrame(oscars)

table['Title'] = oscars
# table.to_csv('../R/others_omdb.csv',encoding= 'utf-8',na_rep='', header= True, index= False, index_label= False)

In [5]:
table

,RT_audience_perc,RT_audience_rating,RT_consensus,RT_perc,RT_rating,awards,imdb_rating,metascore,plot,Title
0,N/A,N/A,N/A,N/A,N/A,Won 3 Oscars. Another 197 wins & 239 nominations.,7.6,99,"Three time periods - young adolescence, mid-te...",{u'plot': u'Three time periods - young adolesc...
1,N/A,N/A,N/A,N/A,N/A,Won 2 Oscars. Another 116 wins & 132 nominations.,8.1,93,"When the Boston Globe's tenacious ""Spotlight"" ...",{u'plot': u'When the Boston Globe's tenacious ...
2,N/A,N/A,N/A,N/A,N/A,N/A,6.9,N/A,A winged superhero who gets his powers from th...,{u'plot': u'A winged superhero who gets his po...
3,N/A,N/A,N/A,N/A,N/A,Won 3 Oscars. Another 234 wins & 320 nominations.,8.1,96,Based on an incredible true story of one man's...,{u'plot': u'Based on an incredible true story ...
4,N/A,N/A,N/A,N/A,N/A,Won 3 Oscars. Another 93 wins & 150 nominations.,7.7,86,"In 1979, the American embassy in Iran was inva...","{u'plot': u'In 1979, the American embassy in I..."
5,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 146 wins & 185 nominations.,7.9,89,"Outside a movie premiere, enthusiastic fan Pep...","{u'plot': u'Outside a movie premiere, enthusia..."
6,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 102 wins & 190 nominations.,8.0,88,England's Prince Albert must ascend the throne...,{u'plot': u'England's Prince Albert must ascen...
7,N/A,N/A,N/A,N/A,N/A,Won 6 Oscars. Another 114 wins & 120 nominations.,7.6,94,An intense portrayal of elite soldiers who hav...,{u'plot': u'An intense portrayal of elite sold...
8,N/A,N/A,N/A,N/A,N/A,Won 8 Oscars. Another 143 wins & 120 nominations.,8.0,86,"The story of Jamal Malik, an 18 year-old orpha...","{u'plot': u'The story of Jamal Malik, an 18 ye..."
9,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 155 wins & 132 nominations.,8.1,91,"In rural Texas, welder and hunter Llewelyn Mos...","{u'plot': u'In rural Texas, welder and hunter ..."
10,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 90 wins & 126 nominations.,8.5,85,"In South Boston, the state police force is wag...","{u'plot': u'In South Boston, the state police ..."
11,N/A,N/A,N/A,N/A,N/A,Won 3 Oscars. Another 62 wins & 106 nominations.,7.8,69,"Over a thirty-six hour period in Los Angeles, ...",{u'plot': u'Over a thirty-six hour period in L...
12,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 63 wins & 78 nominations.,8.1,86,"Wanting to learn from the best, aspiring boxer...","{u'plot': u'Wanting to learn from the best, as..."
13,N/A,N/A,N/A,N/A,N/A,Won 11 Oscars. Another 195 wins & 121 nominati...,8.9,94,The final confrontation between the forces of ...,{u'plot': u'The final confrontation between th...
14,N/A,N/A,N/A,N/A,N/A,Won 6 Oscars. Another 50 wins & 122 nominations.,7.2,82,Murderesses Velma Kelly (a chanteuse and tease...,{u'plot': u'Murderesses Velma Kelly (a chanteu...
15,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 33 wins & 65 nominations.,8.2,72,From the heights of notoriety to the depths of...,{u'plot': u'From the heights of notoriety to t...
16,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 53 wins & 101 nominations.,8.5,64,"Maximus is a powerful Roman general, loved by ...",{u'plot': u'Maximus is a powerful Roman genera...
17,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 103 wins & 96 nominations.,8.4,86,"Lester and Carolyn Burnham are, on the outside...","{u'plot': u'Lester and Carolyn Burnham are, on..."
18,N/A,N/A,N/A,N/A,N/A,Won 7 Oscars. Another 56 wins & 88 nominations.,7.2,87,Will Shakespeare is a known but struggling poe...,{u'plot': u'Will Shakespeare is a known but st...
19,N/A,N/A,N/A,N/A,N/A,Won 11 Oscars. Another 110 wins & 74 nominations.,7.7,74,"84 years later, a 101-year-old woman named Ros...","{u'plot': u'84 years later, a 101-year-old wom..."
20,N/A,N/A,N/A,N/A,N/A,Won 9 Oscars. Another 50 wins & 66 nominations.,7.4,87,"October 1944 in war torn Italy. Hana, a French...",{u'plot': u'October 1944 in war torn Italy. Ha...
21,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 26 wins & 29 nominations.,8.4,68,William Wallace is a Scottish rebel who leads ...,{u'plot': u'William Wallace is a Scottish rebe...
22,N/A,N/A,N/A,N/A,N/A,Won 6 Oscars. Another 39 wins & 65 nominations.,8.8,82,Forrest Gump is a simple man with a low I.Q. b...,{u'plot': u'Forrest Gump is a simple man with ...
23,N/A,N/A,N/A,N/A,N/A,Won 7 Oscars. Another 71 wins & 33 nominations.,8.9,93,Oskar Schindler is a vainglorious and greedy G...,{u'plot': u'Oskar Schindler is a vainglorious ...
24,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 36 wins & 29 nominations.,8.3,82,The town of Big Whisky is full of normal peopl...,{u'plot': u'The town of Big Whisky is full of ...
25,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 48 wins & 36 nominations.,8.6,84,FBI trainee Clarice Starling works hard to adv...,{u'plot': u'FBI trainee Clarice Starling works...
26,N/A,N/A,N/A,N/A,N/A,Won 7 Oscars. Another 43 wins & 33 nominations.,8.0,72,Lt. John Dunbar is dubbed a hero after he acci...,{u'plot': u'Lt. John Dunbar is dubbed a hero a...
27,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 17 wins & 21 nominations.,7.4,81,An elderly Jewish widow living in Atlanta can ...,{u'plot': u'An elderly Jewish widow living in ...
28,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 22 wins & 21 nominations.,8.0,65,"Charles Sanford ""Charlie"" Babbit is a self-cen...","{u'plot': u'Charles Sanford ""Charlie"" Babbit i..."
29,N/A,N/A,N/A,N/A,N/A,Won 9 Oscars. Another 47 wins & 16 nominations.,7.8,76,"This sweeping account of the life of Pu-Yi, th...",{u'plot': u'This sweeping account of the life ...
30,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 19 wins & 14 nominations.,8.1,N/A,"Chris Taylor is a young, naive American who gi...","{u'plot': u'Chris Taylor is a young, naive Ame..."
31,N/A,N/A,N/A,N/A,N/A,Won 7 Oscars. Another 22 wins & 28 nominations.,7.2,N/A,"In 20th-century colonial Kenya, a Danish baron...","{u'plot': u'In 20th-century colonial Kenya, a ..."
32,N/A,N/A,N/A,N/A,N/A,Won 8 Oscars. Another 33 wins & 14 nominations.,8.3,93,Antonio Salieri believes that Wolfgang Amadeus...,{u'plot': u'Antonio Salieri believes that Wolf...
33,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 27 wins & 18 nominations.,7.4,79,Aurora and Emma are mother and daughter who ma...,{u'plot': u'Aurora and Emma are mother and dau...
34,N/A,N/A,N/A,N/A,N/A,Won 8 Oscars. Another 27 wins & 20 nominations.,8.1,N/A,"In 1893, Gandhi is thrown off a South African ...","{u'plot': u'In 1893, Gandhi is thrown off a So..."
35,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 14 wins & 19 nominations.,7.2,N/A,It's the post-WWI era. Britons Harold Abrahams...,{u'plot': u'It's the post-WWI era. Britons Har...
36,N/A,N/A,N/A,N/A,N/A,Won 4 Oscars. Another 15 wins & 14 nominations.,7.8,85,"Beth, Calvin, and their son Conrad are living ...","{u'plot': u'Beth, Calvin, and their son Conrad..."
37,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 32 wins & 23 nominations.,7.8,77,Ted Kramer is a career man for whom his work c...,{u'plot': u'Ted Kramer is a career man for who...
38,N/A,N/A,N/A,N/A,N/A,Won 5 Oscars. Another 17 wins & 26 nominations.,8.2,73,"Michael, Steven and Nick are young factory wor...","{u'plot': u'Michael, Steven and Nick are young..."

In [ ]:
# def getOMDBdata(title):
#     if title == 'Moonlight (2016)':
#         data = omdb.get(title='Moonlight', fullplot=True, tomatoes=True)
#     elif title == "Kramer Vs. Kramer":
#         data = omdb.get(title='Kramer Vs Kramer', fullplot=True, tomatoes=True)
#     else:
#         data = omdb.get(title=title, fullplot=True, tomatoes=True)
    
#     collect = {}
#     collect['awards'] = data['awards']
#     collect['imdb_rating'] = data['imdb_rating'] 
#     collect['metascore'] = data['metascore']
#     collect['plot'] = data['plot']
#     collect['RT_consensus'] = data['tomato_consensus']
#     collect['RT_perc'] = data['tomato_meter']
#     collect['RT_rating'] = data['tomato_rating']
#     collect['RT_audience_perc'] = data['tomato_user_meter']
#     collect['RT_audience_rating'] = data['tomato_user_rating']
    
#     return collect